# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Robust Single-Linkage Clustering
#'
#' @param dists distance matrix (square and symmetric)
#' @param num_clusters the number of clusters to find
#' @param min_size the minimum size of a cluster
#'
#' @return
#'   \item{clusters}{vector with the cluster id (number) for each item}
#'   \item{outliers}{binary vector indicating outliers}
#' @export
#'
#' @example
#' library(rslc)
#' mat <- rbind(cbind(rnorm(10, 5), rnorm(10, 5)), cbind(rnorm(10, -5), rnorm(10, 5)), matrix(rnorm(20), 10, 2), c(-5, 0))
#' cl <- rslc(as.matrix(dist(mat)), 3, 3)
#' plot(mat[, 1], mat[, 2], col=factor(cl$clusters, 0:4), pch=cl$outliers*3+1)
#' legend("topleft", legend = c(paste("Cluster", 1:3), "Outliers"), col = factor(c(1,2,3,0)), pch=c(1,1,1,4))
#'
rslc <- function(dists, num_clusters, min_size) {
    .Call(`_rslc_rslc`, dists, num_clusters, min_size)
}

