[package]
name = "r_rslc"
version = "1.0.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

[lib]
name = "rslc"
crate-type = ["staticlib"]

[dependencies]
rslc = { git = "https://github.com/Aggrathon/rslc/" }
ndarray = "0.13"
