// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rslc
Rcpp::List rslc(const Rcpp::NumericMatrix dists, int num_clusters, int min_size);
RcppExport SEXP _rslc_rslc(SEXP distsSEXP, SEXP num_clustersSEXP, SEXP min_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix >::type dists(distsSEXP);
    Rcpp::traits::input_parameter< int >::type num_clusters(num_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(rslc(dists, num_clusters, min_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rslc_rslc", (DL_FUNC) &_rslc_rslc, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rslc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
