[package]
name = "r_rslc"
version = "0.3.0"
authors = ["Aggrathon <antonbjo@gmail.com>"]
edition = "2018"

[lib]
name = "rslc"
crate-type = ["dylib"]

[dependencies]
rslc = { path = ".." }
extendr-api = "0.1.2"
